# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.csv
flood_scenarios: config/flood_scenarios.csv
parameters space test: config/parameters_space_test.csv
parameters space : config/parameters_space.csv
sectors_common_aggreg: config/sectors_common_aggreg.ods
regions_common_aggreg: config/regions_common_aggreg.ods

testing: False

sim_length: 365
monetary_factor:
  exiobase3_full: 1000000
  oecd_v2021_full: 1000000
  euregio_full: 1000000
  eora26_full:  1000

register_stocks: False

variables:
  - production_realised
  - production_capacity

plot config:
  grid:
    sharey: True
    row order: ["DEU","FRA","CHN","USA","ROW"]

  plot variable name mapping:
    production_realised: production
    final_demand_unmet: final demand not met
    production_capacity: production capacity

  plot types:
    - classic
    - cumsum

  extensions:
    - pdf
    - svg

focus:
  full: {}
#  no_high_psi: {psi: "0.999"}
#  minimal_1: {psi: ["0.999","0.5"], alpha_tau: "30"}

impacts_bins: {'crash': -.inf,
 'L>90%': -100,
 '90%>L>70%': -90,
 '70%>L>50%': -70,
 '50%>L>25%': -50,
 '25%>L>10%': -25,
 '10%>L>5%': -10,
 '5%>L>2%': -5,
 '2%>L>1,5%': -2,
 '1,5%>L>1%': -1.5,
 '1%>L>0,5%': -1,
 '0,5%>L>0%': -0.5,
 'no losses': 0}

gains_bins: {'no gains': -.inf,
 '0%>G>2%': 0,
 '2%>G>5%': 2,
 '5%>G>10%': 5,
 '10%>G>15%': 10,
 '15%>G>20%': 15,
 '20%>G>25%': 20,
 'G>25%': 25}

# % of gva affected for event intensity class
# impact_intensity:
#   high: 0.3
#   med: 0.1
#   low: 0.01
#   germany 2021: 30854

# flood_scenarios:
#   hl: [germany, high, 14]
#   mm: [germany, med, 7]
#   lm: [germany, low, 7]
#   germany21: [germany, germany 2021, 14]

sectors_scenarios:
  exiobase3_full:
    default:
      config/exiobase3_full_sectors.csv
  oecd_v2021_full:
    default:
      config/oecd_v2021_full_sectors.csv
  euregio_full:
    default:
      config/euregio_full_sectors.csv
  eora26_full:
    default:
      config/eora26_full_sectors.csv

recovery_scenarios_mapping:
  recfast: Rapid recovery (capital recovered under 15 days)
  reclin2: Linear recovery in ~2 months
  recS2: S-shaped recovery in ~2months
  reclin6: Linear recovery in ~6months
  recS6: S-shaped recovery in ~6months
  reb15: Very fast paced rebuilding all damages (<15 days tau)
  reb90: Longer rebuilding all damages (90-120 days tau)
  reb15q: Very fast paced rebuilding .25 damages  (<15 days tau)
  reb90q: Longer rebuilding .25 damages (90-120 days tau)

recovery_scenarios:
  recfast:
    - recovery
    - linear
    - 14
  reclin2:
    - recovery
    - linear
    - 60
  recS2:
    - recovery
    - convexe
    - 60
  reclin6:
    - recovery
    - linear
    - 180
  recS6:
    - recovery
    - convexe
    - 180
  reb15:
    - rebuilding
    - 1
    - 14
  reb90:
    - rebuilding
    - 1
    - 90
  reb15q:
    - rebuilding
    - 0.25
    - 14
  reb90q:
    - rebuilding
    - 0.25
    - 90
  reb180:
    - rebuilding
    - 1
    - 180
  reb365:
    - rebuilding
    - 1
    - 365
  reb545:
    - rebuilding
    - 1
    - 545
