# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
testing: True

flood scenario: flood_scenarios/germany21.yaml
simulation space test: simulations/test.yaml
simulation space: simulations/germany21.yaml

sim_length: 1095
register_stocks: False
variables:
  - production_realised
#  - production_capacity

mriot_base_config: "mriot_base_scenarios"

data-mriot:
  prefix: "mriot_data/"
  downloaded_mriot_dir: "downloaded"
  parsed_mriot_dir: "parsed"
  aggregated_mriot_dir: "parsed"
  mriot_params_dir: "config/mriot_params"

  common_aggreg: "common_sectors_common_regions"
  mriot_base_aggreg:
    exiobase3_ixi : "full_sectors_full_regions"
    exiobase3_pxp : "full_sectors_full_regions"
    eora26: "full_no_reexport_sectors_full_regions"
    euregio: "full_sectors_full_regions"

flood scenario params:
  local region: "DEU"


## Following configuration is for advanced use only and should be kept as is in most case ##
impacts_bins_name: {'crash': 'economy crashed',
 'L90': 'losses >90%',
 '90L70': 'losses in 70-90%',
 '70L50': 'losses in 50-70%',
 '50L25': 'losses in 25-50%',
 '25L10': 'losses in 10-25%',
 '10L5': 'losses in 5-10%',
 '5L2': 'losses in 2-5%',
 '2L1_5': 'losses in 1,5-2%',
 '1_5L1': 'losses in 1-1,5%',
 '1L0_5': 'losses in 0,5-1%',
 '0_5L0': 'losses in <0,5%',
 'absurd': 'losses > 10%',
 '0_5L0_25': 'losses in 0,25-0,5%',
 '0_25L0_1': 'losses in 0,1-0,25%',
 '0_1L0': 'losses < 0,1%',
 'no_losses': 'no losses',
 }

impacts_bins: {'crash': -.inf,
 'absurd': -10,
 '5L2': -5,
 '2L1_5': -2,
 '1_5L1': -1.5,
 '1L0_5': -1,
 '0_5L0_25': -0.5,
 '0_25L0_1': -0.25,
 '0_1L0': -0.1,
 'no_losses': 0}

gains_bins: {'no gains': -.inf,
 '0G2': 0,
 '2G5': 2,
 '5G10': 5,
 '10G15': 10,
 '15G20': 15,
 '20G25': 20,
 'G25': 25}

plot config:
  grid:
    sharey: True
    row order: ["DEU","FRA","CHN","USA","ROW"]

  plot variable name mapping:
    production_realised: production
    final_demand_unmet: final demand not met
    production_capacity: production capacity

  plot types:
    - classic
    - cumsum

  extensions:
    - pdf
    - svg

focus:
  all_sim: "all"
  no_absurd: "cumsum_impact_class >= 'absurd'"
