# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
testing: True

flood scenario params:
  local region: "DEU"

data-mriot:
  prefix: "mriot_data/"
  downloaded_mriot_dir: "downloaded"
  parsed_mriot_dir: "parsed"
  aggregated_mriot_dir: "aggregated"
  aggregation_csv_dir: "config/aggregation_files"
  mriot_params_dir: "config/mriot_params"

flood_scenarios: config/flood_scenarios.csv
parameters space test: config/parameters_space_test.csv
parameters space: config/parameters_space.csv
sectors_common_aggreg: config/sectors_common_aggreg.ods
regions_common_aggreg: config/regions_common_aggreg.ods

sectors_scenarios:
  exiobase3_ixi_full:
    default:
      config/mriot_params/exiobase3_ixi_full_sectors.csv
  icio2021_full:
    default:
      config/mriot_params/icio2021_full_sectors.csv
  euregio_full:
    default:
      config/mriot_params/euregio_full_sectors.csv
  eora26_full:
    default:
      config/mriot_params/eora26_full_sectors.csv

sim_length: 100
monetary_factor:
  exiobase3_ixi: 1000000
  icio2021: 1000000
  euregio: 1000000
  eora26:  1000

register_stocks: False

variables:
  - production_realised
#  - production_capacity

plot config:
  grid:
    sharey: True
    row order: ["DEU","FRA","CHN","USA","ROW"]

  plot variable name mapping:
    production_realised: production
    final_demand_unmet: final demand not met
    production_capacity: production capacity

  plot types:
    - classic
    - cumsum

  extensions:
    - pdf
    - svg

focus:
  all_sim: "all"
  no_absurd: "cumsum_impact_class >= 'absurd'"

impacts_bins_name: {'crash': 'economy crashed',
 'L90': 'losses >90%',
 '90L70': 'losses in 70-90%',
 '70L50': 'losses in 50-70%',
 '50L25': 'losses in 25-50%',
 '25L10': 'losses in 10-25%',
 '10L5': 'losses in 5-10%',
 '5L2': 'losses in 2-5%',
 '2L1_5': 'losses in 1,5-2%',
 '1_5L1': 'losses in 1-1,5%',
 '1L0_5': 'losses in 0,5-1%',
 '0_5L0': 'losses in <0,5%',
 'absurd': 'losses > 10%',
 '0_5L0_25': 'losses in 0,25-0,5%',
 '0_25L0_1': 'losses in 0,1-0,25%',
 '0_1L0': 'losses < 0,1%',
 'no_losses': 'no losses',
 }

impacts_bins: {'crash': -.inf,
 'absurd': -10,
 '5L2': -5,
 '2L1_5': -2,
 '1_5L1': -1.5,
 '1L0_5': -1,
 '0_5L0_25': -0.5,
 '0_25L0_1': -0.25,
 '0_1L0': -0.1,
 'no_losses': 0}

gains_bins: {'no gains': -.inf,
 '0G2': 0,
 '2G5': 2,
 '5G10': 5,
 '10G15': 10,
 '15G20': 15,
 '20G25': 20,
 'G25': 25}


recovery_scenarios_mapping:
  reclin3M: Rapid recovery (capital recovered in 3 months)
  reclin6M: Linear recovery in ~6 months
  recS6M: S-shaped recovery in ~6 months
  reclin1Y: Linear recovery in ~1 year
  reclin1_5Y: Linear recovery in ~1_5 year
  reclin2y: Linear recovery in ~2 years
  recS1Y: S-shaped recovery in ~1 year
  recS1_5Y: S-shaped recovery in ~1_5 year
  recS6M: S-shaped recovery in ~6 months
  reb3M: 3 months rebuilding (90 days tau)
  reb6M: 6 months rebuilding (180 days tau)
  reb1Y: 1 year rebuilding (365 days tau)
  reb1_5Y: 1,5 year rebuilding (545 days tau)
  reb2Y: 2 years rebuilding (730 days tau)

recovery_scenarios:
  reclin3M:
    - recovery
    - linear
    - 90
  reclin6M:
    - recovery
    - linear
    - 180
  recS6M:
    - recovery
    - convexe
    - 180
  reclin1Y:
    - recovery
    - linear
    - 365
  reclin2Y:
    - recovery
    - linear
    - 730
  recS1Y:
    - recovery
    - convexe
    - 365
  reclin1_5Y:
    - recovery
    - linear
    - 545
  recS1_5Y:
    - recovery
    - convexe
    - 545
  reb3M:
    - rebuilding
    - 1
    - 90
  reb6M:
    - rebuilding
    - 1
    - 180
  reb1Y:
    - rebuilding
    - 1
    - 365
  reb1_5Y:
    - rebuilding
    - 1
    - 545
  reb2Y:
    - rebuilding
    - 1
    - 730
