# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.csv
flood_scenarios: config/flood_scenarios.csv
parameters space test: config/parameters_space_test.csv
parameters space: config/parameters_space.csv
sectors_common_aggreg: config/sectors_common_aggreg.ods
regions_common_aggreg: config/regions_common_aggreg.ods

testing: False

flood scenario params:
  local region: "DEU"

sim_length: 730
monetary_factor:
  exiobase3_full: 1000000
  oecd_v2021_full: 1000000
  euregio_full: 1000000
  eora26_full:  1000

register_stocks: False

variables:
  - production_realised
#  - production_capacity

plot config:
  grid:
    sharey: True
    row order: ["DEU","FRA","CHN","USA","ROW"]

  plot variable name mapping:
    production_realised: production
    final_demand_unmet: final demand not met
    production_capacity: production capacity

  plot types:
    - classic
    - cumsum

  extensions:
    - pdf
    - svg

focus:
  all_sim: {}
#  no_high_psi: {psi: "0.999"}
#  minimal_1: {psi: ["0.999","0.5"], alpha_tau: "30"}
impacts_bins_name: {'crash': 'economy crashed',
 'L90': 'losses >90%',
 '90L70': 'losses in 70-90%',
 '70L50': 'losses in 50-70%',
 '50L25': 'losses in 25-50%',
 '25L10': 'losses in 10-25%',
 '10L5': 'losses in 5-10%',
 '5L2': 'losses in 2-5%',
 '2L1_5': 'losses in 1,5-2%',
 '1_5L1': 'losses in 1-1,5%',
 '1L0_5': 'losses in 0,5-1%',
 '0_5L0': 'losses in <0,5%',
 'absurd': 'losses > 10%',
 '0_5L0_25': 'losses in 0,25-0,5%',
 '0_25L0_1': 'losses in 0,1-0,25%',
 '0_1L0': 'losses < 0,1%',
 'no_losses': 'no losses',
 }

impacts_bins: {'crash': -.inf,
 'absurd': -10,
 '5L2': -5,
 '2L1_5': -2,
 '1_5L1': -1.5,
 '1L0_5': -1,
 '0_5L0_25': -0.5,
 '0_25L0_1': -0.25,
 '0_1L0': -0.1,
 'no_losses': 0}

gains_bins: {'no gains': -.inf,
 '0G2': 0,
 '2G5': 2,
 '5G10': 5,
 '10G15': 10,
 '15G20': 15,
 '20G25': 20,
 'G25': 25}

# % of gva affected for event intensity class
# impact_intensity:
#   high: 0.3
#   med: 0.1
#   low: 0.01
#   germany 2021: 30854

# flood_scenarios:
#   hl: [germany, high, 14]
#   mm: [germany, med, 7]
#   lm: [germany, low, 7]
#   germany21: [germany, germany 2021, 14]

sectors_scenarios:
  exiobase3_full:
    default:
      config/exiobase3_full_sectors.csv
  oecd_v2021_full:
    default:
      config/oecd_v2021_full_sectors.csv
  euregio_full:
    default:
      config/euregio_full_sectors.csv
  eora26_full:
    default:
      config/eora26_full_sectors.csv

recovery_scenarios_mapping:
  recfast: Rapid recovery (capital recovered under 15 days)
  reclin2: Linear recovery in ~2 months
  recS2: S-shaped recovery in ~2months
  reclin6: Linear recovery in ~6months
  recS6: S-shaped recovery in ~6months
  reb15: Very fast paced rebuilding all damages (15 days tau)
  reb90: Longer rebuilding all damages (90 days tau)
  reb15q: Very fast paced rebuilding .25 damages  (15 days tau)
  reb90q: Longer rebuilding .25 damages (90 days tau)
  reb365: Very long rebuilding (365 days tau)
  reb545: Extremely long rebuilding (545 days tau)

recovery_scenarios:
  recfast:
    - recovery
    - linear
    - 14
  reclin2:
    - recovery
    - linear
    - 60
  recS2:
    - recovery
    - convexe
    - 60
  reclin6:
    - recovery
    - linear
    - 180
  recS6:
    - recovery
    - convexe
    - 180
  reb15:
    - rebuilding
    - 1
    - 14
  reb90:
    - rebuilding
    - 1
    - 90
  reb15q:
    - rebuilding
    - 0.25
    - 14
  reb90q:
    - rebuilding
    - 0.25
    - 90
  reb180:
    - rebuilding
    - 1
    - 180
  reb365:
    - rebuilding
    - 1
    - 365
  reb545:
    - rebuilding
    - 1
    - 545
